[build]
  command = "bun run build && mkdir -p build && cp -r out/* build/"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]
